name = "SolveBeliefMDP"
uuid = "20fd60d1-d4af-4119-affe-637e1a748328"
authors = ["Himanshu Gupta"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
